POST http://localhost:3001/api/login
content-type: application/json

{
  "email": "123@test.ca",
  "password": "secret"
}

###

POST http://localhost:3001/api/register
content-type: application/json

{
  "username": "bob",
  "email": "123@test.ca",
  "password": "secret"
}
